[build]
  publish = "public"
  functions = "netlify/functions"

# Reindirizza tutte le chiamate API alla nostra funzione serverless
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
